spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/my_test_db
    username: springpostgre_user
    password: 123

  liquibase:
    change-log: classpath:liquibase/migration.yml

  jpa:
    open-in-view: off
#    properties:
#      jakarta.persistence.lock.timeout: 0


#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

